# This is a basic workflow to help you get started with Actions

name: Test pandoc

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[noaction]')"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Create directory
      run: [[ -d docs ]] || mkdir docs

    # Runs a set of commands using the runners shell
    - name: Run docker
      uses: docker://pandoc/latex:2.9
      with:
          args: "--standalone --output=docs/README.pdf README.md"
    - name: Add files
      run: |
        git add docs/README.pdf
    - name: push files
      uses: EndBug/add-and-commit@v4
      with: 
        message: '[noaction] Generated PDF'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: upload
      uses: actions/upload-artifact@master
      with:
          name: docs
          path: docs
